text_classification:
  # Swahili News Dataset
  - name: swahili_news
    languages_covered:
      - swahili
    num_labels: 6
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/swahili_news
    label2id: {kitaifa: 1, michezo: 2, kimataifa: 3, burudani: 4, afya: 5}
   
   # Hausa VOA Topics
  - name: hausa_voa_topics
    languages_covered:
      - hausa
    num_labels: 5
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/hausa_voa_topics
    label2id: {Africa: 0, Health: 1, Nigeria: 2, Politics: 3, World: 4}
    
   # Yoruba BBC Topics
  - name: yoruba_bbc_topics
    languages_covered:
      - Yoruba
    num_labels: 7
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/yoruba_bbc_topics
    label2id: {africa: 0, entertainment: 1, health: 2, nigeria: 3, politics: 4, sport: 5, world: 6}


 # Swahili Tweet Sentiment
  - name: Davis/Swahili-tweet-sentiment
    languages_covered:
      - Swahili
    num_labels: 3 #0,1,-1
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/Davis/Swahili-tweet-sentiment
    
  # Yoruba Movie Reviews
  - name: Iyanuoluwa/YOSM
    languages_covered:
      - Yoruba
    num_labels: 2 #positive, negative
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/Iyanuoluwa/YOSM
   
# Wikipedia Language Identification 
  - name: wili_2018
    languages_covered:
      - ace
      - af
      - als
      - am
      - an
      - ang
      - ar
      - arz
      - as
      - ast
      - av
      - ay
      - az
      - azb
      - ba
      - bar
      - bcl
      - be
      - bg
      - bho
      - bjn
      - bn
      - bo
      - bpy
      - br
      - bs
      - bxr
      - ca
      - cbk
      - cdo
      - ce
      - ceb
      - chr
      - ckb
      - co
      - crh
      - cs
      - csb
      - cv
      - cy
      - da
      - de
      - diq
      - dsb
      - dty
      - dv
      - egl
      - el
      - en
      - eo
      - es
      - et
      - eu
      - ext
      - fa
      - fi
      - fo
      - fr
      - frp
      - fur
      - fy
      - ga
      - gag
      - gd
      - gl
      - glk
      - gn
      - gu
      - gv
      - ha
      - hak
      - he
      - hi
      - hif
      - hr
      - hsb
      - ht
      - hu
      - hy
      - ia
      - id
      - ie
      - ig
      - ilo
      - io
      - is
      - it
      - ja
      - jam
      - jbo
      - jv
      - ka
      - kaa
      - kab
      - kbd
      - kk
      - km
      - kn
      - ko
      - koi
      - kok
      - krc
      - ksh
      - ku
      - kv
      - kw
      - ky
      - la
      - lad
      - lb
      - lez
      - lg
      - li
      - lij
      - lmo
      - ln
      - lo
      - lrc
      - lt
      - ltg
      - lv
      - lzh
      - mai
      - map
      - mdf
      - mg
      - mhr
      - mi
      - min
      - mk
      - ml
      - mn
      - mr
      - mrj
      - ms
      - mt
      - mwl
      - my
      - myv
      - mzn
      - nan
      - nap
      - nb
      - nci
      - nds
      - ne
      - new
      - nl
      - nn
      - nrm
      - nso
      - nv
      - oc
      - olo
      - om
      - or
      - os
      - pa
      - pag
      - pam
      - pap
      - pcd
      - pdc
      - pfl
      - pl
      - pnb
      - ps
      - pt
      - qu
      - rm
      - ro
      - roa
      - ru
      - rue
      - rup
      - rw
      - sa
      - sah
      - sc
      - scn
      - sco
      - sd
      - sgs
      - sh
      - si
      - sk
      - sl
      - sme
      - sn
      - so
      - sq
      - sr
      - srn
      - stq
      - su
      - sv
      - sw
      - szl
      - ta
      - tcy
      - te
      - tet
      - tg
      - th
      - tk
      - tl
      - tn
      - to
      - tr
      - tt
      - tyv
      - udm
      - ug
      - uk
      - ur
      - uz
      - vec
      - vep
      - vi
      - vls
      - vo
      - vro
      - wa
      - war
      - wo
      - wuu
      - xh
      - xmf
      - yi
      - yo
      - zea
      - zh
    num_labels: 235 
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/wili_2018
    label2id: {'0': cdo, '1': glk, '2': jam, '3': lug, '4': san, '5': rue, '6': wol, '7': new, '8': mwl
            '9': bre,'10': ara,'11': hye, '12': xmf, '13': ext, '14': cor, '15': yor, '16': div, '17': asm, '18': lat
            '19': cym,'20': hif, '21': ace, '22': kbd, '23': tgk, '24': rus,'25': nso,'26': mya, '27': msa,'28': ava, 
            '29': cbk, '30': urd, '31': deu, '32': swa, '33': pus, '34': bxr, '35': udm,'36': csb, '37': yid, '38': vro, 
            '39': por, '40': pdc, '41': eng,'42': tha,'43': hat,'44': lmo,'45': pag,'46': jav,'47': chv,'48': nan, '49': sco, '50': kat,'51': bho
            '52': bos,'53': kok, '54': oss, '55': mri, '56': fry, '57': cat, '58': azb, '59': kin, '60': hin, '61': sna, '62': dan, '63': egl
            '64': mkd, '65': ron, '66': bul, '67': hrv, '68': som, '69': pam, '70': nav, '71': ksh, '72': nci, '73': khm., '74': sgs, '75': srn, '76': bar, '77': cos, '78': ckb, '79': pfl, '80': arz, '81': roa-tara, '82': fra
            '83': mai, '84': zh-yue, '85': guj, '86': fin, '87': kir, '88': vol, '89': hau, '90': afr, '91': uig, '92': lao, '93': swe, '94': slv, '95': kor, '96': szl, '97': srp, '98': dty, '99': nrm,'100': dsb
            '101': ind, '102': wln, '103': pnb, '104': ukr, '105': bpy, '106': vie, '107': tur,  '108': aym
            '109': lit, '110': zea, '111': pol, '112': est, '113': scn, '114': vls, '115': stq, '116': gag, '117': grn, '118': kaz, '119': ben, '120': pcd, '121': bjn, '122': krc, '123': amh, '124': diq,  '125': ltz, '126': ita, '127': kab
            '128': bel, '129': ang, '130': mhr, '131': che, '132': koi, '133': glv, '134': ido, '135': fao,  '136': bak, '137': isl, '138': bcl, '139': tet, '140': jpn
            '141': kur, '142': map-bms, '143': tyv, '144': olo, '145': arg,'146': ori, '147': lim, '148': tel, '149': lin, '150': roh, '151': sqi
            '152': xho, '153': mlg,  '154': fas, '155': hbs, 
            '156': tam, '157': aze, '158': lad, '159': nob,'160': sin, 
            '161': gla, '162': nap, '163': snd, '164': ast, '165': mal, '166': mdf, '167': tsn, '168': nds, '169': tgl, '170': nno, '171': sun, '172': lzh, '173': jbo, '174': crh, '175': pap, '176': oci, '177': hak, '178': uzb, '179': zho, '180': hsb, '181': sme, '182': mlt, 
            '183': vep, '184': lez, '185': nld, '186': nds-nl, 
            '187': mrj, '188': spa, 
            '189': ceb, '190': ina, '191': heb, '192': hun, '193': que, '194': kaa, 
            '195': mar, '196': vec, '197': frp, '198': ell, '199': sah, '200': eus, '201': ces, '202': slk, '203': chr, '204': lij, '205': nep, '206': srd, '207': ilo, '208': be-tarask, '209': bod, '210': orm, '211': war, '212': glg,
            '213': mon, '214': gle, '215': min, '216': ibo, '217': ile, '218': epo, '219': lav, '220': lrc, '221': als, '222': mzn, '223': rup, '224': fur, '225': tat, '226': myv, '227': pan, '228': ton, '229': kom, '230': wuu, 
            '231': tcy, '232': tuk, '233': kan, '234': ltg}

ner:
  # Masakhaner Version 1
  - name: masakhaner
    languages_covered:
      - amharic
      - hausa
      - igbo
      - ganda
      - luo
      - pidgin
      - kinyarwanda
      - swahili
      - wolof
      - yoruba
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/masakhaner
  # Masakhaner Version 2
  - name: masakhaner2
    languages_covered:
      - amharic
      - hausa
      - igbo
      - ganda
      - luo
      - pidgin
      - kinyarwanda
      - swahili
      - wolof
      - yoruba
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/masakhane/masakhaner2

