text_classification:
  # Swahili News Dataset
  - name: swahili_news
    languages_covered:
      - swahili
    num_labels: 6
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/swahili_news
    label2id: {utumi: 0, kitaifa: 1, michezo: 2, kimataifa: 3, burudani: 4, afya: 5}
    text_feature_name: text
    label_feature_name: label
    label_mapped: true
   
   # Hausa VOA Topics
  - name: hausa_voa_topics
    languages_covered:
      - hausa
    num_labels: 5
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/hausa_voa_topics
    label2id: {Africa: 0, Health: 1, Nigeria: 2, Politics: 3, World: 4}
    text_feature_name: news_title
    label_feature_name: label
    label_mapped: true
    
   # Yoruba BBC Topics
  - name: yoruba_bbc_topics
    languages_covered:
      - Yoruba
    num_labels: 7
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/yoruba_bbc_topics
    label2id: {africa: 0, entertainment: 1, health: 2, nigeria: 3, politics: 4, sport: 5, world: 6}
    text_feature_name: news_title
    label_feature_name: label
    label_mapped: true


 # Swahili Tweet Sentiment
  - name: swahili-tweet-sentiment
    languages_covered:
      - Swahili
    num_labels: 3
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/Davis/Swahili-tweet-sentiment
    text_feature_name: news_title
    label_feature_name: label
    label_mapped: true
    
  # Yoruba Movie Reviews
  - name: yosm
    languages_covered:
      - Yoruba
    num_labels: 2 #positive, negative
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/Iyanuoluwa/YOSM
   
ner:
  # Masakhaner Version 1
  - name: masakhaner
    languages_covered:
      - amharic
      - hausa
      - igbo
      - ganda
      - luo
      - pidgin
      - kinyarwanda
      - swahili
      - wolof
      - yoruba
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/masakhaner
  # Masakhaner Version 2
  - name: masakhaner2
    languages_covered:
      - amharic
      - hausa
      - igbo
      - ganda
      - luo
      - pidgin
      - kinyarwanda
      - swahili
      - wolof
      - yoruba
    available_on_huggingface: true
    dataset_link: https://huggingface.co/datasets/masakhane/masakhaner2

